### Get Media Albums
GET {{HostAddress}}/media-albums

### Get Media Album By Id
GET {{HostAddress}}/media-albums/d43e433e-f36b-1410-8919-00414d3e33ca

### Get Media Album By Name
GET {{HostAddress}}/media-albums/test-media-album-1